-- ==============================================
-- 1️⃣ Tables
-- ==============================================

-- Members Table
CREATE TABLE members (
    member_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_name VARCHAR2(50) UNIQUE,
    member_role VARCHAR2(10) CHECK (member_role IN ('ADMIN', 'USER'))
);

-- Files Table
CREATE TABLE files (
    file_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR2(100),
    owner_member_id NUMBER REFERENCES members(member_id),
    visibility VARCHAR2(10) CHECK (visibility IN ('PUBLIC', 'PRIVATE'))
);

-- Action Log Table
CREATE TABLE action_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER,
    file_id NUMBER,
    action_type VARCHAR2(20),
    status_msg VARCHAR2(15),
    action_time DATE DEFAULT SYSDATE
);


-- ==============================================
-- 2️⃣ Package Specification
-- ==============================================

CREATE OR REPLACE PACKAGE pkg_file_management IS

    -- Procedures
    PROCEDURE add_member(p_name IN VARCHAR2, p_role IN VARCHAR2);
    PROCEDURE add_file(p_name IN VARCHAR2, p_owner_id IN NUMBER, p_visibility IN VARCHAR2);
    PROCEDURE log_action(p_member_id IN NUMBER, p_file_id IN NUMBER, p_action IN VARCHAR2, p_status IN VARCHAR2);

    -- Functions
    FUNCTION get_member_role(p_member_id NUMBER) RETURN VARCHAR2;
    FUNCTION count_member_files(p_member_id NUMBER) RETURN NUMBER;
    FUNCTION is_file_public(p_file_id NUMBER) RETURN VARCHAR2;

END pkg_file_management;
/

-- ==============================================
-- 3️⃣ Package Body
-- ==============================================

CREATE OR REPLACE PACKAGE BODY pkg_file_management IS

    -- Add a new member
    PROCEDURE add_member(p_name IN VARCHAR2, p_role IN VARCHAR2) IS
    BEGIN
        INSERT INTO members(member_name, member_role)
        VALUES(p_name, p_role);
        COMMIT;
    END add_member;

    -- Add a new file
    PROCEDURE add_file(p_name IN VARCHAR2, p_owner_id IN NUMBER, p_visibility IN VARCHAR2) IS
    BEGIN
        INSERT INTO files(file_name, owner_member_id, visibility)
        VALUES(p_name, p_owner_id, p_visibility);
        COMMIT;
    END add_file;

    -- Log an action
    PROCEDURE log_action(p_member_id IN NUMBER, p_file_id IN NUMBER, p_action IN VARCHAR2, p_status IN VARCHAR2) IS
    BEGIN
        INSERT INTO action_log(member_id, file_id, action_type, status_msg)
        VALUES(p_member_id, p_file_id, p_action, p_status);
        COMMIT;
    END log_action;

    -- Get member role
    FUNCTION get_member_role(p_member_id NUMBER) RETURN VARCHAR2 IS
        v_role VARCHAR2(10);
    BEGIN
        SELECT member_role INTO v_role
        FROM members
        WHERE member_id = p_member_id;
        RETURN v_role;
    END get_member_role;

    -- Count files owned by a member
    FUNCTION count_member_files(p_member_id NUMBER) RETURN NUMBER IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count
        FROM files
        WHERE owner_member_id = p_member_id;
        RETURN v_count;
    END count_member_files;

    -- Check file visibility
    FUNCTION is_file_public(p_file_id NUMBER) RETURN VARCHAR2 IS
        v_visibility VARCHAR2(10);
    BEGIN
        SELECT visibility INTO v_visibility
        FROM files
        WHERE file_id = p_file_id;
        RETURN v_visibility;
    END is_file_public;

END pkg_file_management;
/

-- ==============================================
-- 4️⃣ Triggers
-- ==============================================

-- Trigger: Log file addition automatically
CREATE OR REPLACE TRIGGER trg_after_file_insert
AFTER INSERT ON files
FOR EACH ROW
BEGIN
    pkg_file_management.log_action(
        p_member_id => :NEW.owner_member_id,
        p_file_id   => :NEW.file_id,
        p_action    => 'ADD_FILE',
        p_status    => 'SUCCESS'
    );
END;
/

-- Trigger: Prevent deletion of ADMIN members
CREATE OR REPLACE TRIGGER trg_no_admin_delete
BEFORE DELETE ON members
FOR EACH ROW
DECLARE
    v_role VARCHAR2(10);
BEGIN
    v_role := pkg_file_management.get_member_role(:OLD.member_id);

    IF v_role = 'ADMIN' THEN
        RAISE_APPLICATION_ERROR(-20001, 'Cannot delete ADMIN members');
    END IF;
END;
/

-- Trigger: Update action log timestamp when status changes
CREATE OR REPLACE TRIGGER trg_update_action_time
BEFORE UPDATE OF status_msg ON action_log
FOR EACH ROW
BEGIN
    :NEW.action_time := SYSDATE;
END;
/



-- ==============================================
-- 1️⃣ Insert Members using package
-- ==============================================

BEGIN
    pkg_file_management.add_member('Alice', 'ADMIN');
    pkg_file_management.add_member('Bob', 'USER');
    pkg_file_management.add_member('Charlie', 'USER');
END;
/
-- Check members
SELECT * FROM members;

-- ==============================================
-- 2️⃣ Insert Files using package
-- ==============================================

BEGIN
    -- Alice adds a public file
    pkg_file_management.add_file('Project_Plan.docx', 1, 'PUBLIC');

    -- Bob adds a private file
    pkg_file_management.add_file('Bob_Notes.txt', 2, 'PRIVATE');

    -- Charlie adds a public file
    pkg_file_management.add_file('Charlie_Report.pdf', 3, 'PUBLIC');
END;
/
-- Check files
SELECT * FROM files;

-- ==============================================
-- 3️⃣ Manually log an action (optional)
-- ==============================================

BEGIN
    pkg_file_management.log_action(2, 1, 'VIEW_FILE', 'SUCCESS');
    pkg_file_management.log_action(3, 2, 'EDIT_FILE', 'FAILED');
END;
/
-- Check action log
SELECT * FROM action_log ORDER BY action_time DESC;

-- ==============================================
-- 4️⃣ Check Functions
-- ==============================================

-- Count files owned by Bob (member_id=2)
SELECT pkg_file_management.count_member_files(2) AS bob_file_count FROM dual;

-- Check if file_id=1 is public
SELECT pkg_file_management.is_file_public(1) AS file_visibility FROM dual;

-- Get role of Alice (member_id=1)
SELECT pkg_file_management.get_member_role(1) AS alice_role FROM dual;
-- ==============================================
-- 1️⃣ Insert more files using the package
-- ==============================================

BEGIN
    -- Alice adds more files
    pkg_file_management.add_file('Alice_Plan_v2.docx', 1, 'PRIVATE');
    pkg_file_management.add_file('Alice_Report.xlsx', 1, 'PUBLIC');

    -- Bob adds more files
    pkg_file_management.add_file('Bob_Project.docx', 2, 'PUBLIC');
    pkg_file_management.add_file('Bob_Drafts.txt', 2, 'PRIVATE');

    -- Charlie adds more files
    pkg_file_management.add_file('Charlie_Notes.docx', 3, 'PRIVATE');
    pkg_file_management.add_file('Charlie_Summary.pdf', 3, 'PUBLIC');
END;
/
-- Check updated files
SELECT * FROM files ORDER BY file_id;

-- ==============================================
-- 2️⃣ Insert more action logs (manual inserts)
-- ==============================================

BEGIN
    -- Bob views Alice's file
    pkg_file_management.log_action(2, 1, 'VIEW_FILE', 'SUCCESS');

    -- Charlie edits Bob's file
    pkg_file_management.log_action(3, 4, 'EDIT_FILE', 'SUCCESS');

    -- Alice views Charlie's file
    pkg_file_management.log_action(1, 6, 'VIEW_FILE', 'SUCCESS');

    -- Bob deletes a file (manual action log)
    pkg_file_management.log_action(2, 5, 'DELETE_FILE', 'SUCCESS');

    -- Charlie attempts to edit Alice's private file
    pkg_file_management.log_action(3, 4, 'EDIT_FILE', 'FAILED');
END;
/
-- Check updated action log
SELECT * FROM action_log ORDER BY action_time DESC;

select * from files;
select * from action_log;

SELECT 
    f.file_id,
    f.file_name,
    f.owner_member_id,
    m.member_name,
    ROW_NUMBER() OVER (PARTITION BY f.owner_member_id ORDER BY f.file_id) AS file_rank
FROM files f
JOIN members m ON f.owner_member_id = m.member_id
ORDER BY f.owner_member_id, file_rank;


SELECT 
    a.member_id,
    m.member_name,
    COUNT(*) OVER (PARTITION BY a.member_id) AS total_actions
FROM action_log a
JOIN members m ON a.member_id = m.member_id
ORDER BY a.member_id;

SELECT *
FROM (
    SELECT 
        a.file_id,
        f.file_name,
        a.member_id,
        m.member_name,
        a.action_type,
        a.status_msg,
        a.action_time,
        ROW_NUMBER() OVER (PARTITION BY a.file_id ORDER BY a.action_time DESC) AS rn
    FROM action_log a
    JOIN files f ON a.file_id = f.file_id
    JOIN members m ON a.member_id = m.member_id
) 
WHERE rn = 1;

SELECT *
FROM (
    SELECT 
        m.member_id,
        m.member_name,
        COUNT(f.file_id) AS total_files,
        RANK() OVER (ORDER BY COUNT(f.file_id) DESC) AS member_rank
    FROM members m
    LEFT JOIN files f ON m.member_id = f.owner_member_id
    GROUP BY m.member_id, m.member_name
) 
ORDER BY member_rank;
